Extend http.ServerResponse
kyranet/http-nextra pull request #2
Opened 2018-04-01 15:54 UTC by TortleOG

### Description of the PR
This PR extends `http.ServerResponse` to add helper methods for ease of use. `APIServer` and `http.IncomingMessage` are accessible on the extended class. Also adds automatic response header building through `new APIServer(serverOptions, listener)`. This PR only includes support for a fair amount of headers, but not all of them. Headers are built once on server startup. Also adds routes in test/server.js for the helper methods.

### Areas That Need Work
- `ResponseNextra#sendFile`
  - Currently uses `fs.readFileSync` because it was the only method that didn't error out. Will happily change in favour of a better solution
- `headerBuilder.js`
  - Needs in-depth testing to see if all headers set properly

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)
- Extend http.ServerResponse
- Add many helper methods
- Add test routes
- Add automatic header building

### Semver Classification
- [ ] This PR only includes documentation or non-code changes.
- [ ] This PR fixes a bug and does not change the (intended) framework interface.
- [x] This PR adds methods or properties to the framework interface.
- [ ] This PR removes or renames methods or properties in the framework interface.

2018-04-01 16:25 UTC, kyranet requested changes

2018-04-01 16:25 UTC, kyranet commented on src/APIServer.js
> +	constructor(options = {}, listener) {
Options should be last argument.

2018-04-01 16:25 UTC, kyranet commented on src/ResponseNextra.js
> +const MIMETYPES = {
Should be exported as `ResponseNextra.MIMETYPES`. Possibly move it to constants and allow the developer modify them to add more values.

2018-04-01 16:25 UTC, kyranet commented on test/server.js
> +const server = new APIServer(undefined, async (request, response) => {
Remove the `undefined` with the first requested change.

2018-04-07 18:47 UTC, TortleOG commented
This PR should be pretty much finished, in terms of code changes. Only things that may need changing is better error checking in options.headers building. This PR also now relies on PR (#1) to properly sendFiles.

2018-04-07 18:53 UTC, TortleOG commented
Now it's finished 😄

2018-04-07 19:49 UTC, KingDGrizzle commented
I'll be home tommorow so expect #1 to be done and merge-ready ~unless kyra does the edits cause I have allow maintainers to edit enabled~

2018-04-08 08:34 UTC, MrJacz commented on src/ResponseNextra.js
> +	end(data) {
Should use `...args` considering end takes 1, 2 or 3 arguments

2018-04-09 23:14 UTC, TortleOG commented
Alright, I have made all the changes I want to make. This PR should be good to go, and header options should be error proof, but you never know! 👍

2018-04-13 10:38 UTC, merged